<?php
/**
 * Default layout, used to render most parts of the application
 *
 * @category backoffice
 * @package backoffice_layouts
 * @copyright company
 */

// configure the title
$this->headTitle()->setSeparator(' - ');
$this->headTitle('company Backoffice');

// add generic CSS files
$this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap.min.css');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/master.css');

$this->headScript()->appendFile($this->baseUrl() . '/js/libs/bootstrap.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/backoffice.js');

//Add the ZFDebug Toolbar only if enabled in app.ini
if(Zend_Controller_Front::getInstance()->hasPlugin('ZFDebug_Controller_Plugin_Debug')){
    $this->headScript()->offsetSetFile(2, $this->baseUrl() . '/js/libs/zfdebug.js');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/zfdebug.css');
}

$user = Zend_Auth::getInstance()->getIdentity();

$bodyClass = Zend_Registry::get('controllerName') . Zend_Registry::get('actionName');

$this->AutoloadResources();

?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
        
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  
  
  <meta name="viewport" content="width=device-width">
  
  <script src="<?php echo $this->baseUrl(); ?>/js/libs/modernizr-2.5.2.min.js"></script>  
        
  <link rel="shortcut icon" type="image/ico" href="<?php echo $this->baseUrl();?>/images/favicon.png" />
        
  <?php echo $this->headTitle() . PHP_EOL;?>
  <?php echo $this->headLink() . PHP_EOL;?>
        
</head>
<body class="<?php echo $bodyClass;?>"  data-spy="scroll" data-target=".subnav" data-offset="50" >

    
    <div class="navbar navbar-fixed-top clearix">
       <div class="navbar-inner">
         <div class="container">
           
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a> 
           
          <a title="Company BackOffice" class="brand" href="<?php echo $this->baseUrl();?>/">Company <span>BackOffice</span></a>
            
            <div class="nav-collapse">
              <?php echo $this->renderMenu();?>

              <ul class="nav pull-right">
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" ><?php echo $user->firstname . ' ' . $user->lastname;?> <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->baseUrl();?>/profile/edit/" >Edit</a></li>
                    <li><a href="<?php echo $this->baseUrl();?>/profile/change-password/">Change password</a></li>
                    <li><a id="logout" href="<?php echo $this->baseUrl();?>/profile/logout/">Log Out</a></li>
                  </ul>
                </li>
              </ul> 
            </div>
            
         </div>
       </div>
     </div>

    
    <div class="container">
        
      <header class="jumbotron subhead" id="overview">
        <h1><?php echo $this->title; ?></h1>

        <div class="subnav">
          <?php echo $this->renderSubMenu();?>
        </div>      
      </header>  

      <div id="content">
        <!-- flash messenger - displays success / fail messages to the user -->
        <?php echo $this->flashMessenger();?>                
        <!-- main content - the content of the view will be rendered here -->
        <?php echo $this->layout()->content;?>
      </div>



      <footer class="footer">
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>© Company BackOffice — <?= date('Y') ?></p>
      </footer>
    
    </div><!-- /container -->
  
    <!-- add the js files -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl(); ?>/js/libs/jquery-1.7.1.min.js"><\/script>')</script>    
    <?php echo $this->headScript() . PHP_EOL;?>
  
    </body> 
</html>