<?php
/**
 * Layout used to display error pages
 *
 * @category backoffice
 * @package backoffice_layouts
 * @copyright company
 */

// configure the title
$this->headTitle()->setSeparator(' - ');
$this->headTitle('company');

// add generic scripts
$this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap.min.css');
$this->headLink()->appendStylesheet($this->baseUrl().'/css/master.css');

$this->headScript()->appendFile($this->baseUrl() . '/js/libs/bootstrap.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/backoffice.js');


//Add the ZFDebug Toolbar only if enabled in app.ini
if(App_DI_Container::get('ConfigObject')->zfdebug->enabled){
    $this->headScript()->appendFile($this->baseUrl() . '/js/zfdebug.js');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/zfdebug.css');
}
?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
        
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  
  
  <meta name="viewport" content="width=device-width">
  
  <script src="<?php echo $this->baseUrl(); ?>/js/libs/modernizr-2.5.2.min.js"></script>  
        
  <link rel="shortcut icon" type="image/ico" href="<?php echo $this->baseUrl();?>/images/favicon.png" />
        
        <?php echo $this->headTitle() . PHP_EOL;?>
        <?php echo $this->headLink() . PHP_EOL;?>       
        

</head>
<body id="loginPage">
      
  <div class="row-fluid">
      
    <header id="loginHeader">
      <h1>Backoffice</h1>
    </header>
      
    <div id="content" class="clearfix">
      <!-- main content - the content of the view will be rendered here -->
      <?php echo $this->layout()->content;?>
    </div>

    
  </div><!-- /container -->      
      
    <!-- add the js files -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl(); ?>/js/libs/jquery-1.7.1.min.js"><\/script>')</script>    
    <?php echo $this->headScript() . PHP_EOL;?>      
        <script type="text/javascript" charset="utf-8"> 
            //Set focus on username field
            $(document).ready(function() {
                $('input#username').focus();
            });
        </script>       
    
    </body>
</html>