<?php
/**
 * View that defines the default add/edit UI 
 *
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage partials
 * @copyright Company
 */

$helper = $this->listingUtilities($this->config);

?>
<div class="box altbox"> 
    <div class="boxin"> 
        <div class="header"> 
            <h1><?php $helper->pageTitle();?></h1>
        </div> 
        <?php echo $this->form;?>
    </div> 
</div>

