<?php
/**
 * View for the default item details UI
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage partials
 * @copyright company
 */

$helper = $this->listingUtilities($this->config);
?>
<header class="page-header"> 
    <h1><?php $helper->pageTitle();?></h1>  
</header>

<div class="finalaction">
    <table class="table table-striped table-bordered table-condensed">
        <?php $indexes = array_combine($helper->getColumnNames(), $helper->getColumnIndexes()) ?>
        <?php foreach($helper->getColumnNamesAndValues($this->item) as $columnName => $columnValue) : ?>
            <tr>
                <th valign="top"><?php echo $columnName;?>:</th>
                <td><?php $helper->displayItem($columnValue, $indexes[$columnName]);?></td>
            </tr>
        <?php endforeach;?>
    </table>
    <p class="back"><a class="alt" href="<?php echo $this->config['backlink'];?>">← Go back</a></p>
</div>