<?php
/**
 * View for the default deleting UI
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage partials
 * @copyright company
 */

$helper = $this->listingUtilities($this->config);
?>

<header class="page-header"> 
    <h1><?php $helper->pageTitle();?></h1>  
</header>

<div class="finalaction">
    <h2><?php $helper->areYouSureMessage();?></h2>
    <table class="table table-striped table-bordered table-condensed">
        <?php foreach($helper->getColumnNamesAndValues($this->item) as $columnName => $columnValue) : ?>  
            <tr>
                <th><?php $helper->displayItem($columnName);?>:</th>
                <td><?php $helper->displayItem($columnValue);?></td>
            </tr>
        <?php endforeach;?>
    </table>
    <?php echo $this->form;?>
</div>