<?php
/**
 * Default layout, used to render most parts of the application
 *
 * @package frontend_layouts
 * @copyright Company
 */

//Configure the title
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Company');

//Add generic scripts
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/ddpng.js');

//Add generic CSS files
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/main.css');

//Add the ZFDebug Toolbar only if enabled in app.ini
if(Zend_Registry::get('config')->zfdebug->enabled){
    $this->headScript()->appendFile($this->baseUrl() . '/js/zfdebug.js');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/zfdebug.css');
}
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
    
    <?php echo $this->headTitle() . PHP_EOL;?>
    <?php echo $this->headLink() . PHP_EOL;?>
    
    <!-- Adding support for transparent PNGs in IE6: --> 
    <!--[if lte IE 6]>
        <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/ddpng.js"></script>
        <script type="text/javascript">
            DD_belatedPNG.fix('.png');
        </script>
    <![endif]-->
    
    <!-- add the js files -->
    <?php echo $this->headScript() . PHP_EOL;?>
</head>
<body>
    <div id="page">
        <div id="header">
            <?php echo $this->partial('partials/header.phtml'); ?>
        </div>
        
        <?php echo $this->layout()->content;?>
        
        <div id="footer">
            <?php echo $this->partial('partials/footer.phtml'); ?>
        </div>
    </div>
</body>
</html>