<?php
/**
 * Default layout, used to render most parts of the application
 *
 * @package frontend_layouts
 * @copyright company
 */

//Configure the title
$this->headTitle()->setSeparator(' - ');
$this->headTitle('company');

//Add generic CSS files
$this->headLink()->appendStylesheet($this->baseUrl().'/css/master.css');

//Add the ZFDebug Toolbar only if enabled in app.ini
if(Zend_Controller_Front::getInstance()->hasPlugin('ZFDebug_Controller_Plugin_Debug')){
    $this->headScript()->appendFile($this->baseUrl() . '/js/libs/zfdebug.js');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/zfdebug.css');
}

//Autoload js files
$this->AutoloadResources();
?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  

     
  <?php echo $this->headTitle() . PHP_EOL;?>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headLink() . PHP_EOL;?>  
  
  <meta name="viewport" content="width=device-width">
  
  <script src="<?php echo $this->baseUrl(); ?>/js/libs/modernizr-2.5.2.min.js"></script>
    
  <link rel="shortcut icon" type="image/ico" href="/images/favicon.png" />
    
       
    
</head>
<body>
<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->  
  
  <header>
    <?php echo $this->partial('partials/header.phtml'); ?>
  </header> 
  
  <div role="main">
  <?php echo $this->flashMessenger();?>
  <?php echo $this->layout()->content;?>
  </div>
  
  <footer>
    <?php echo $this->partial('partials/footer.phtml'); ?>
  </footer>  
  
  
    <!-- add the js files -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl(); ?>/js/libs/jquery-1.7.1.min.js"><\/script>')</script>    
    <?php echo $this->headScript() . PHP_EOL;?>

    
    <?php if(Zend_Registry::get('IS_PRODUCTION')) : ?>
        <?php echo $this->partial('partials/ga.phtml'); ?>
    <?php endif; ?>
    
</body>
</html>