<?php
/**
 * Displays the 404 - Page not found error
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_error
 * @copyright Company
 */
?>

<div class="box box-100"><!-- box full-width --> 
    <div class="boxin"> 
        <div id="errorpage" class="clearfix">
            <!--<img class="cat" src="<?php echo $this->baseUrl();?>/css/img/error-404-02.gif" alt="Error 404">-->
            <h1>Page not found</h1>
            <p>
                The URL you requested was not found.
            </p>
            <p><a class="alt" href="javascript:history.back();">← Go back</a></p>
        </div>
    </div> 
</div>
<script type="text/javascript" charset="utf-8">
    // Random 404 lolcats
    $(document).ready(function(){
        var imgTotal=2;
        var randomNumber = Math.round(Math.random()*(imgTotal-1))+1;
        var imgPath=('/images/error-404-0'+randomNumber+'.gif');
        var img = $("<img>").attr({
            'src': '<?php echo $this->baseUrl();?>/images/error-404-0' + randomNumber + '.gif',
            'class': 'error404',
            'alt': 'Error 404',
            });
        $('div#errorpage').prepend(img);
    });
</script>


