<?php
/**
 * Holds the default paginator view
 *
 *
 * @category backoffice
 * @package backoffice_paginators
 * @copyright Company
 */
?>
<?php if ($this->pageCount): ?>
    <ul class="pagination">
        <li>
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a class="text" href="<?php echo $this->url(array('page' => $this->previous)); ?>"> &larr; Previous</a>
        <?php else: ?>
            <span class="disabled"> &larr; Previous</span>
        <?php endif; ?>
        </li>
        
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <li>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
            <?php else: ?>
                <span class="current"><?php echo $page; ?></span>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
        
        <!-- Next page link -->
        <li>
        <?php if (isset($this->next)): ?>
            <a class="text" href="<?php echo $this->url(array('page' => $this->next)); ?>">Next &rarr;</a>
        <?php else: ?>
            <span class="disabled">Next &rarr;</span>
        <?php endif; ?>
    </li>
    </ul>
<?php endif; ?>