<?php
/**
 * Holds the default paginator view
 *
 *
 * @category backoffice
 * @package backoffice_paginators
 * @copyright company
 */
?>
<?php if ($this->pageCount): ?>
<div class="pagination pagination-centered">
    <ul>
      <li <?php if (!isset($this->previous)): ?>class="disabled"<?php endif; ?> >
        <!-- Previous page link -->
        <a class="text" href="<?php echo $this->url(array('page' => $this->previous)); ?>">←</a>
      </li>
        
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
        <li <?php if ($page == $this->current): ?>class="active"<?php endif; ?> >
          <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
        </li>
        <?php endforeach; ?>
        
        <!-- Next page link -->
    <li <?php if (!isset($this->next)): ?>class="disabled"<?php endif; ?> >
      <a class="text" href="<?php echo $this->url(array('page' => $this->next)); ?>">→</a>
    </li>
  </ul>
</div>
<?php endif; ?>